title: S-G-Lee GitBlog
description: 이제 막 개발자로 태어나려는 사람의 블로그입니다.
author: SGLee
avatar: /myphoto.jpg
email: qowppp@gmail.com
lang: ko

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: S-G-Lee
  card: summary
logo: myphoto.jpg
social:
  name: SGLee
  links:
    #- https://twitter.com/ngzhio
    #- https://www.facebook.com/ngzhio
    - https://github.com/S-G-Lee
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
